-- Entity Vault: Database and Schema Setup
-- Run this script first to create all database objects.

-- =============================================================================
-- DATABASE
-- =============================================================================
CREATE OR REPLACE DATABASE ENTITY_VAULT_DB
    COMMENT = 'Entity Vault - Identity Resolution, Encoding, and Enrichment Platform';

-- =============================================================================
-- SCHEMAS
-- =============================================================================
CREATE SCHEMA ENTITY_VAULT_DB.CORE
    COMMENT = 'Golden record entities, identifiers, and type schemas';

CREATE SCHEMA ENTITY_VAULT_DB.RESOLUTION
    COMMENT = 'AI-powered resolution: embeddings, search service, resolution procedures';

CREATE SCHEMA ENTITY_VAULT_DB.ENCODING
    COMMENT = 'Namespaces, HMAC key management, and encoded ID mappings';

CREATE SCHEMA ENTITY_VAULT_DB.ENRICHMENT
    COMMENT = 'Entity groups, contributions, and marketplace catalog';

CREATE SCHEMA ENTITY_VAULT_DB.POLICY
    COMMENT = 'Consent records, suppression records, and transcode policies';

CREATE SCHEMA ENTITY_VAULT_DB.AUDIT
    COMMENT = 'Immutable audit trail for all vault operations';

-- =============================================================================
-- CORE TABLES
-- =============================================================================
CREATE TABLE ENTITY_VAULT_DB.CORE.ENTITY_TYPE_SCHEMAS (
    SCHEMA_ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL,
    CLASS_NAME VARCHAR(100) NOT NULL,
    CLASS_LABEL VARCHAR(200),
    CLASS_DESCRIPTION VARCHAR(1000),
    PARENT_NAME VARCHAR(100),
    ATTRIBUTES VARIANT,
    RESOLUTION_CONFIG VARIANT,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_ENTITY_TYPE_SCHEMAS PRIMARY KEY (SCHEMA_ID),
    CONSTRAINT UQ_CLASS_NAME UNIQUE (CLASS_NAME)
);

CREATE TABLE ENTITY_VAULT_DB.CORE.ENTITIES (
    ENTITY_ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL,
    ENTITY_TYPE VARCHAR(50) NOT NULL,
    LIFECYCLE_STATE VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    TRUST_TIER VARCHAR(20) DEFAULT 'STANDARD',
    METADATA VARIANT DEFAULT PARSE_JSON('{}'),
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    DELETED_AT TIMESTAMP_LTZ,
    CONSTRAINT PK_ENTITIES PRIMARY KEY (ENTITY_ID)
);

CREATE TABLE ENTITY_VAULT_DB.CORE.IDENTIFIERS (
    IDENTIFIER_ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL,
    ENTITY_ID VARCHAR(36) NOT NULL,
    IDENTIFIER_TYPE VARCHAR(50) NOT NULL,
    IDENTIFIER_VALUE VARCHAR(500),
    NORMALIZED_VALUE_HASH VARCHAR(128) NOT NULL,
    SOURCE_SYSTEM VARCHAR(100),
    CONFIDENCE_SCORE FLOAT DEFAULT 1.0,
    LINK_TYPE VARCHAR(30) DEFAULT 'DETERMINISTIC',
    FIRST_SEEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_SEEN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    METADATA VARIANT DEFAULT PARSE_JSON('{}'),
    CONSTRAINT PK_IDENTIFIERS PRIMARY KEY (IDENTIFIER_ID),
    CONSTRAINT FK_IDENTIFIERS_ENTITY FOREIGN KEY (ENTITY_ID) REFERENCES ENTITY_VAULT_DB.CORE.ENTITIES(ENTITY_ID)
);

ALTER TABLE ENTITY_VAULT_DB.CORE.IDENTIFIERS CLUSTER BY (NORMALIZED_VALUE_HASH);

-- =============================================================================
-- ENCODING TABLES
-- =============================================================================
CREATE TABLE ENTITY_VAULT_DB.ENCODING.NAMESPACES (
    NAMESPACE_ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL,
    NAMESPACE_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    OWNER_ORG VARCHAR(200),
    CLEARANCE_LEVEL VARCHAR(20) DEFAULT 'ENRICHMENT',
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_NAMESPACES PRIMARY KEY (NAMESPACE_ID),
    CONSTRAINT UQ_NAMESPACE_NAME UNIQUE (NAMESPACE_NAME)
);

CREATE TABLE ENTITY_VAULT_DB.ENCODING.NAMESPACE_KEY_VERSIONS (
    KEY_VERSION_ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL,
    NAMESPACE_ID VARCHAR(36) NOT NULL,
    VERSION_NUMBER INTEGER NOT NULL,
    HMAC_SECRET_ENCRYPTED VARCHAR(500) NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    ROTATED_AT TIMESTAMP_LTZ,
    CONSTRAINT PK_NAMESPACE_KEY_VERSIONS PRIMARY KEY (KEY_VERSION_ID),
    CONSTRAINT FK_NKV_NAMESPACE FOREIGN KEY (NAMESPACE_ID) REFERENCES ENTITY_VAULT_DB.ENCODING.NAMESPACES(NAMESPACE_ID)
);

CREATE TABLE ENTITY_VAULT_DB.ENCODING.NAMESPACE_ENCODINGS (
    ENCODING_ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL,
    ENTITY_ID VARCHAR(36) NOT NULL,
    NAMESPACE_ID VARCHAR(36) NOT NULL,
    ENCODED_ID VARCHAR(128) NOT NULL,
    KEY_VERSION_ID VARCHAR(36) NOT NULL,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_NAMESPACE_ENCODINGS PRIMARY KEY (ENCODING_ID),
    CONSTRAINT UQ_ENTITY_NAMESPACE UNIQUE (ENTITY_ID, NAMESPACE_ID)
);

ALTER TABLE ENTITY_VAULT_DB.ENCODING.NAMESPACE_ENCODINGS CLUSTER BY (ENCODED_ID, NAMESPACE_ID);

-- =============================================================================
-- ENRICHMENT TABLES
-- =============================================================================
CREATE TABLE ENTITY_VAULT_DB.ENRICHMENT.ENTITY_GROUPS (
    GROUP_ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL,
    GROUP_NAME VARCHAR(200) NOT NULL,
    GROUP_DESCRIPTION VARCHAR(1000),
    ENTITY_TYPE VARCHAR(50) NOT NULL,
    CREATED_BY_NAMESPACE_ID VARCHAR(36) NOT NULL,
    CATEGORY_SCHEMA VARIANT,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    IS_DISCOVERABLE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_ENTITY_GROUPS PRIMARY KEY (GROUP_ID),
    CONSTRAINT UQ_GROUP_NAME UNIQUE (GROUP_NAME)
);

CREATE TABLE ENTITY_VAULT_DB.ENRICHMENT.ENTITY_GROUP_MEMBERS (
    MEMBER_ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL,
    GROUP_ID VARCHAR(36) NOT NULL,
    ENTITY_ID VARCHAR(36) NOT NULL,
    CATEGORY_VALUE VARCHAR(200),
    ASSIGNED_BY_NAMESPACE_ID VARCHAR(36) NOT NULL,
    ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_ENTITY_GROUP_MEMBERS PRIMARY KEY (MEMBER_ID),
    CONSTRAINT FK_EGM_GROUP FOREIGN KEY (GROUP_ID) REFERENCES ENTITY_VAULT_DB.ENRICHMENT.ENTITY_GROUPS(GROUP_ID),
    CONSTRAINT UQ_GROUP_ENTITY UNIQUE (GROUP_ID, ENTITY_ID)
);

CREATE TABLE ENTITY_VAULT_DB.ENRICHMENT.GROUP_ACCESS_GRANTS (
    GRANT_ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL,
    GROUP_ID VARCHAR(36) NOT NULL,
    NAMESPACE_ID VARCHAR(36) NOT NULL,
    ACCESS_LEVEL VARCHAR(20) DEFAULT 'READ',
    GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    GRANTED_BY_NAMESPACE_ID VARCHAR(36) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CONSTRAINT PK_GROUP_ACCESS_GRANTS PRIMARY KEY (GRANT_ID),
    CONSTRAINT FK_GAG_GROUP FOREIGN KEY (GROUP_ID) REFERENCES ENTITY_VAULT_DB.ENRICHMENT.ENTITY_GROUPS(GROUP_ID)
);

CREATE TABLE ENTITY_VAULT_DB.ENRICHMENT.CONTRIBUTION_SCHEMAS (
    SCHEMA_ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL,
    SCHEMA_NAME VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    ENTITY_TYPE VARCHAR(50) NOT NULL,
    NAMESPACE_ID VARCHAR(36) NOT NULL,
    FIELD_DEFINITIONS VARIANT,
    IS_DISCOVERABLE BOOLEAN DEFAULT TRUE,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CONTRIBUTION_SCHEMAS PRIMARY KEY (SCHEMA_ID),
    CONSTRAINT UQ_CONTRIB_SCHEMA_NAME UNIQUE (SCHEMA_NAME)
);

CREATE TABLE ENTITY_VAULT_DB.ENRICHMENT.ENTITY_CONTRIBUTIONS (
    CONTRIBUTION_ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL,
    ENTITY_ID VARCHAR(36) NOT NULL,
    SCHEMA_ID VARCHAR(36) NOT NULL,
    NAMESPACE_ID VARCHAR(36) NOT NULL,
    ATTRIBUTES VARIANT NOT NULL,
    CONTRIBUTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_ENTITY_CONTRIBUTIONS PRIMARY KEY (CONTRIBUTION_ID),
    CONSTRAINT FK_EC_SCHEMA FOREIGN KEY (SCHEMA_ID) REFERENCES ENTITY_VAULT_DB.ENRICHMENT.CONTRIBUTION_SCHEMAS(SCHEMA_ID)
);

ALTER TABLE ENTITY_VAULT_DB.ENRICHMENT.ENTITY_CONTRIBUTIONS CLUSTER BY (ENTITY_ID, SCHEMA_ID);

CREATE TABLE ENTITY_VAULT_DB.ENRICHMENT.CONTRIBUTION_ACCESS_GRANTS (
    GRANT_ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL,
    SCHEMA_ID VARCHAR(36) NOT NULL,
    NAMESPACE_ID VARCHAR(36) NOT NULL,
    ACCESS_LEVEL VARCHAR(20) DEFAULT 'READ',
    GRANTED_BY_NAMESPACE_ID VARCHAR(36) NOT NULL,
    GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CONSTRAINT PK_CONTRIBUTION_ACCESS_GRANTS PRIMARY KEY (GRANT_ID),
    CONSTRAINT FK_CAG_SCHEMA FOREIGN KEY (SCHEMA_ID) REFERENCES ENTITY_VAULT_DB.ENRICHMENT.CONTRIBUTION_SCHEMAS(SCHEMA_ID)
);

-- =============================================================================
-- POLICY TABLES
-- =============================================================================
CREATE TABLE ENTITY_VAULT_DB.POLICY.CONSENT_RECORDS (
    CONSENT_ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL,
    ENTITY_ID VARCHAR(36) NOT NULL,
    NAMESPACE_ID VARCHAR(36) NOT NULL,
    CONSENT_TYPE VARCHAR(50) NOT NULL,
    GRANTED_BY VARCHAR(100),
    GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    EXPIRES_AT TIMESTAMP_LTZ,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CONSTRAINT PK_CONSENT_RECORDS PRIMARY KEY (CONSENT_ID)
);

CREATE TABLE ENTITY_VAULT_DB.POLICY.SUPPRESSION_RECORDS (
    SUPPRESSION_ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL,
    ENTITY_ID VARCHAR(36) NOT NULL,
    SUPPRESSION_TYPE VARCHAR(50) NOT NULL,
    REASON VARCHAR(500),
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    EXPIRES_AT TIMESTAMP_LTZ,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CONSTRAINT PK_SUPPRESSION_RECORDS PRIMARY KEY (SUPPRESSION_ID)
);

CREATE TABLE ENTITY_VAULT_DB.POLICY.TRANSCODE_POLICIES (
    POLICY_ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL,
    SOURCE_NAMESPACE_ID VARCHAR(36) NOT NULL,
    TARGET_NAMESPACE_ID VARCHAR(36) NOT NULL,
    POLICY_TYPE VARCHAR(50) DEFAULT 'ALLOW',
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CONSTRAINT PK_TRANSCODE_POLICIES PRIMARY KEY (POLICY_ID)
);

-- =============================================================================
-- AUDIT TABLE
-- =============================================================================
CREATE TABLE ENTITY_VAULT_DB.AUDIT.AUDIT_LOG (
    AUDIT_ID VARCHAR(36) DEFAULT UUID_STRING() NOT NULL,
    OPERATION VARCHAR(50) NOT NULL,
    ENTITY_ID VARCHAR(36),
    NAMESPACE_ID VARCHAR(36),
    TARGET_NAMESPACE_ID VARCHAR(36),
    GROUP_ID VARCHAR(36),
    INPUT_DATA VARIANT,
    OUTPUT_DATA VARIANT,
    RESOLUTION_TIER VARCHAR(20),
    CONFIDENCE_SCORE FLOAT,
    ALTERNATIVES VARIANT,
    POLICY_RESULT VARCHAR(20),
    PERFORMED_BY VARCHAR(100),
    PERFORMED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (AUDIT_ID)
);

-- =============================================================================
-- RESOLUTION TABLES
-- =============================================================================
CREATE TABLE ENTITY_VAULT_DB.RESOLUTION.ENTITY_EMBEDDINGS (
    ENTITY_ID VARCHAR(36) NOT NULL,
    ENTITY_TYPE VARCHAR(50),
    SEARCH_TEXT VARCHAR(16000),
    EMBEDDING VECTOR(FLOAT, 1024),
    EMBEDDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_ENTITY_EMBEDDINGS PRIMARY KEY (ENTITY_ID)
);

-- =============================================================================
-- VIEWS
-- =============================================================================
CREATE OR REPLACE VIEW ENTITY_VAULT_DB.RESOLUTION.ENTITIES_SEARCHABLE AS
SELECT
    e.ENTITY_ID,
    e.ENTITY_TYPE,
    CONCAT_WS(' | ',
        CASE WHEN e.METADATA:i_brand::VARCHAR IS NOT NULL THEN 'brand: ' || e.METADATA:i_brand::VARCHAR END,
        CASE WHEN e.METADATA:i_category::VARCHAR IS NOT NULL THEN 'category: ' || e.METADATA:i_category::VARCHAR END,
        CASE WHEN e.METADATA:i_class::VARCHAR IS NOT NULL THEN 'class: ' || e.METADATA:i_class::VARCHAR END,
        CASE WHEN e.METADATA:i_manufact::VARCHAR IS NOT NULL THEN 'manufacturer: ' || e.METADATA:i_manufact::VARCHAR END,
        CASE WHEN e.METADATA:i_product_name::VARCHAR IS NOT NULL THEN 'product: ' || e.METADATA:i_product_name::VARCHAR END,
        CASE WHEN e.METADATA:i_color::VARCHAR IS NOT NULL THEN 'color: ' || e.METADATA:i_color::VARCHAR END,
        CASE WHEN e.METADATA:i_size::VARCHAR IS NOT NULL THEN 'size: ' || e.METADATA:i_size::VARCHAR END
    ) AS SEARCH_TEXT
FROM ENTITY_VAULT_DB.CORE.ENTITIES e
WHERE e.LIFECYCLE_STATE = 'ACTIVE';

CREATE OR REPLACE VIEW ENTITY_VAULT_DB.ENRICHMENT.VW_ENTITY_ALL_ATTRIBUTES AS
SELECT
    e.ENTITY_ID,
    'PLATFORM_GOLDEN_RECORD' AS SCHEMA_NAME,
    NULL AS NAMESPACE_ID,
    e.METADATA AS ATTRIBUTES,
    e.CREATED_AT AS CONTRIBUTED_AT
FROM ENTITY_VAULT_DB.CORE.ENTITIES e
WHERE e.LIFECYCLE_STATE = 'ACTIVE'
UNION ALL
SELECT
    ec.ENTITY_ID,
    cs.SCHEMA_NAME,
    ec.NAMESPACE_ID,
    ec.ATTRIBUTES,
    ec.CONTRIBUTED_AT
FROM ENTITY_VAULT_DB.ENRICHMENT.ENTITY_CONTRIBUTIONS ec
JOIN ENTITY_VAULT_DB.ENRICHMENT.CONTRIBUTION_SCHEMAS cs ON ec.SCHEMA_ID = cs.SCHEMA_ID
QUALIFY ROW_NUMBER() OVER (PARTITION BY ec.ENTITY_ID, ec.SCHEMA_ID ORDER BY ec.CONTRIBUTED_AT DESC) = 1;
